apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: api-es
spec:
  refreshInterval: 1s           # rate SecretManager pulls GCPSM
  secretStoreRef:
    kind: ClusterSecretStore
    name: secret-store-sample         # name of the SecretStore (or kind specified)
  target:
    name: secret-to-be-created  # name of the k8s Secret to be created
    creationPolicy: Owner
  # dataFrom:
  # - key: apisecret  # name of the GCPSM secret
  data:
  - secretKey: my-secret  # name of the GCPSM secret key
    remoteRef:
      key: my-secret


# apiVersion: kubernetes-client.io/v1
# kind: ExternalSecret
# metadata:
#   name: my-gcp-secret #name of the External Secret and the generate k8s secret
# spec:
#   backendType: gcpSecretsManager
#   projectId: gke-practice-341914
#   data:
#     - key: my-secret # name of the GCP secret
#       version: latest # version of the GCP secret
#       property: value # name of the field in the GCP secret
#       name: secret-key # key name in the k8s secret




# apiVersion: secrets-store.csi.x-k8s.io/v1
# kind: SecretProviderClass
# metadata:
#   name: gcp-secrets
#   namespace: dev
# spec:
#   provider: gcp
#   secretObjects:
#   - secretName: api-token-env-10
#     type: Opaque
#     data: 
#     - objectName: TEST_SECRET_ID
#       key: test-secret-contents
#     # - objectName: apisecret2.txt
#     #   key: test-secret-contents2
#   parameters:
#     secrets: |
#       - resourceName: "projects/gke-practice-share/secrets/apisecret/versions/latest"
#         path: "TEST_SECRET_ID"
# - resourceName: "projects/gke-practice-share/secrets/apisecret/versions/latest"
#   path: "apisecret2.txt"

# gke-practice-341914

# spec:
#   provider: gcp
#   secretObjects:
#   - secretName: cbci-mc-secret
#     type: Opaque
#     data: 
#     - objectName: token
#       key: token
#   parameters:
#     secrets: |
#       - resourceName: "projects/core-workshop/secrets/cbci-workshop-token/versions/latest"
#         fileName: "token"

# ---
# apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
# kind: SecretProviderClass
# metadata:
#   name: aws-secrets
#   namespace: production
# spec:
#   provider: aws
#   secretObjects:
#   - secretName: api-token
#     type: Opaque
#     data: 
#     - objectName: secret-token
#       key: SECRET_TOKEN
#   parameters:
#     objects: |
#       - objectName: prod/service/token
#         objectType: secretsmanager
#         objectAlias: secret-token
