apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: nginx
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nginx
  minReplicas: 1
  maxReplicas: 4
  targetCPUUtilizationPercentage: 40

# metrics:
# - type: Resource
#   resource:
#     name: cpu
#     target:
#      type: Utilication
#      averageUtilization: 40
# metrics:
# - type: Resource
#   resource:
#     name: memory
#     target:
#      type: AverageValue
#      averageUtilization: 100Mi
# metrics:
# - type: Pods
#   pods:
#     metric:
#       name: packets-per-second
#     target:
#      type: AverageValue
#      averageUtilization: 1k

# kubectl autoscale deployment nginx --cpu-percentage=40 --min=1 --max=5