apiVersion: v1
kind: Service
metadata:
  name: mongo-svc
  namespace: mongodb
  labels:
    app: mongo
spec:
  type: LoadBalancer
  selector:
    app: mongo 
  ports:
  - name: mongo
    port: 27017
    targetPort: 27017
