apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-mysql-master
  labels:
    app: mysql-master
data:
  my.cnf: |
    # Apply this config only on the primary.
    # [mysql]
    server-id = 1
    log_bin = mysql-bin
    binlog_do_db = flaskapp 
