apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-mysql-slave
  labels:
    app: mysql-slave
data:
  my.cnf: |
    # Apply this config only on the primary.
    # [mysql]
    server-id = 3
    log_bin = mysql-bin
    binlog_do_db = flaskapp 
