apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: gcp-secrets
  namespace: dev
spec:
  provider: gcp
  secretObjects:
  - secretName: api-token-env-10
    type: Opaque
    data: 
    - objectName: TEST_SECRET_ID
      key: test-secret-contents
    # - objectName: apisecret2.txt
    #   key: test-secret-contents2
  parameters:
    secrets: |
      - resourceName: "projects/gke-practice-share/secrets/apisecret/versions/12"
        path: "TEST_SECRET_ID"
# - resourceName: "projects/gke-practice-share/secrets/apisecret/versions/latest"
#   path: "apisecret2.txt"

# gke-practice-341914

# spec:
#   provider: gcp
#   secretObjects:
#   - secretName: cbci-mc-secret
#     type: Opaque
#     data: 
#     - objectName: token
#       key: token
#   parameters:
#     secrets: |
#       - resourceName: "projects/core-workshop/secrets/cbci-workshop-token/versions/latest"
#         fileName: "token"

# ---
# apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
# kind: SecretProviderClass
# metadata:
#   name: aws-secrets
#   namespace: production
# spec:
#   provider: aws
#   secretObjects:
#   - secretName: api-token
#     type: Opaque
#     data: 
#     - objectName: secret-token
#       key: SECRET_TOKEN
#   parameters:
#     objects: |
#       - objectName: prod/service/token
#         objectType: secretsmanager
#         objectAlias: secret-token
