apiVersion: v1
kind: Service
metadata:
  name: flask-pod-nodeport-service 
spec:
  type: NodePort 
  selector:
    app: flask-app 
  ports: 
    - name: http
      port: 80 # Service Port
      targetPort: 5000 # Container Port
      nodePort: 31213 # NodePort


