apiVersion: v1
kind: Pod
metadata:
  name: flask-app-pod
  labels: 
    app: flask-app  
spec:
  containers: 
    - name: flask-app-container
      image: akhilmovva/flask-image:latest
      env: 
        - name: ENV
          value: "dev"
        - name: MYSQL_HOST
          value: "10.100.233.112"
      ports:
        - containerPort: 5000