---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      # serviceAccountName: nginx
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
        env:
        - name: API_TOKEN
          valueFrom:
            secretKeyRef:
              name: my-gcp-secret
              key: secret-key
      # volumes:
      # - name: my-api-token
      #   secret:
      #     secretName: my-gcp-secret


# apiVersion: v1
# kind: Pod
# metadata:
#   name: mypod
#   namespace: default
# spec:
#   serviceAccountName: mypodserviceaccount
#   containers:
#   - image: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
#     imagePullPolicy: IfNotPresent
#     name: mypod
#     resources:
#       requests:
#         cpu: 100m
#     stdin: true
#     stdinOnce: true
#     terminationMessagePath: /dev/termination-log
#     terminationMessagePolicy: File
#     tty: true
#     volumeMounts:
#       - mountPath: "/var/secrets"
#         name: mysecret
#   volumes:
#   - name: mysecret
#     csi:
#       driver: secrets-store.csi.k8s.io
#       readOnly: true
#       volumeAttributes:
#         secretProviderClass: "app-secrets"
