apiVersion: v1
kind: Service
metadata:
  name: flask-nodeport-service-blue-green
  labels: 
    app: flask-app-service
spec:
  type: NodePort #LoadBalancer  
  selector:
    app: flask-app-green
  ports: 
    - name: http
      port: 80 # Service Port
      targetPort: 5000 # Container Port
      nodePort: 31213 # NodePort