apiVersion: v1
kind: PersistentVolume
metadata: 
  name: mysql-volume-ebs
  labels:
    type: amazonEBS
spec: 
  #kubectl get storageclass
  storageClassName: gp2
  capacity:
    storage: 1Gi
  accessModes: 
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"