apiVersion: v1
kind: Secret
metadata:
  name: google-creds
type: Opaque
stringData:
  .env: |
    ID=1
    APP_SECRET_KEY='very secret key'
    GOOGLE_CLIENT_ID='*****************'
    GOOGLE_CLIENT_SECRET='**************'