apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: mysql-pv-claim
spec: 
  #kubectl get storageclass
  storageClassName: efs
  accessModes: 
    - ReadWriteMany
  resources: 
    requests: 
      storage: 100Mi